language: java


# command to run tests
before_script:
   - mkdir bin
   - export CLASSPATH=junitUtils/junit-4.11.jar:junitUtils/hamcrest-core-1.3.jar:src/:bin/

script: 

   - javac -d bin src/test/CalculadoraTest.java 
   - java org.junit.runner.JUnitCore test.CalculadoraTest